@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc1JlZnJlc2giOmZhbHNlLCJyb2xlSWRzIjpbIjEiXSwidXNlcm5hbWUiOiJhZG1pbiIsInVzZXJJZCI6MSwicGFzc3dvcmRWZXJzaW9uIjozLCJpYXQiOjE2MjQ0NTgxNjQsImV4cCI6MTYyNDQ2NTM2NH0.jQXzTNK_nAwpYhlTAKvVzkFzZYd0Dnz-7bqgPqaWtBo


###
GET http://127.0.0.1:8001/api/test/1?id=1&name=a
content-type: application/json
Authorization: {{token}}
###

###
GET http://127.0.0.1:8001/api/test/3?id=1&name=a
content-type: application/json
Authorization: {{token}}
###

###
POST http://127.0.0.1:8001/api/test/4
content-type: application/json
Authorization: {{token}}

{
    "id": 11,
    "name": "aa"
}
###

###
POST http://127.0.0.1:8001/app/demo/goods/list
content-type: application/json
Authorization: {{token}}
###

###
GET http://127.0.0.1:8001/api/test/5
###
